export const REGISTER_USER = "REGISTER_USER";
export const CLEAN_REGISTER = "CLEAN_REGISTER";
export const AGREGAR_SALDO = "AGREGAR_SALDO";
export const CONSULTAR_SALDO = "CONSULTAR_SALDO";
export const REALIZAR_PAGO = "REALIZAR_PAGO";
export const LIMPIAR_PAGO = "LIMPIAR_PAGO";
export const COMPROBAR_TOKEN = "COMPROBAR_TOKEN";
